# .github/workflows/test-parent.yml
name: 01-Test-Parent

on:
  push:
    branches:
      - dev

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Parent workflow has finished."